apiVersion: batch/v1
kind: Job
metadata:
  name: snyk-iac-scan-snyk-boot-web
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: snyk-cli
          image: snyk/snyk-cli:npm
          command: ["/bin/sh","-c"]
          args:
            - git clone https://github.com/papicella/snyk-boot-web;
              snyk auth $SNYK_TOKEN;
              snyk iac test snyk-boot-web/argocd/snyk-boot-app-v1.yaml || true;
              snyk container test pasapples/snyk-boot-web:v1 --severity-threshold=critical || true;
              echo "all done";
          env:
            - name: SNYK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: snyk-token
                  key: token
      restartPolicy: Never
  backoffLimit: 0